### ISSUE TITLE
Pattern matching for paths and extensions

### ISSUE THREAD

**Issue by pitkes22** [BlueFrog130/vite-plugin-barrels#1]
Hi, very nice and useful plugin :+1: 

It would be great if `entry` and `extension` would support patterns like `lib/components/*` or `lib/components/**` to be able to specify if I wand barrel file for only one level of directories or for all nested folders.

Also for me, it's a dealbreaker for me that I can't exclude some files/folders. For example I need to exclude all story-book stories. With pattern matching, it would be possible (`*.tsx` will not match `foo.stories.tsx`).

**Comment by BlueFrog130** [comment]
#2 fixes this, extension name now allows for regex

**Comment by shoveller** [comment]
hello @BlueFrog130.
Can you release a package that reflects #2?

**Comment by BlueFrog130** [comment]
@shoveller
My bad on the delay. Published `1.1.0`.

Should set up an action to auto publish on merge...
